#!/bin/sh

# debian
apt-get install perl

perl -MCPAN -e 'install HTML::TagParser' # not in debian
apt-get install libhtml-linkextractor-perl libwww-perl libwww-perl liburi-perl libcss-perl libhttp-date-perl libgetopt-long-descriptive-perl

apt-get install curl libcurl3 libcurl3-dev

apt-get install python

# fedora
yum install perl

perl -MCPAN -e 'install HTML::TagParser'
perl -MCPAN -e 'install HTML::LinkExtractor'
perl -MCPAN -e 'install HTTP::Cookies'
perl -MCPAN -e 'install HTTP::Status'
perl -MCPAN -e 'install URI'
perl -MCPAN -e 'install CSS'
perl -MCPAN -e 'install HTTP::Date'
perl -MCPAN -e 'install Getopt::Long'

yum install curl

yum install python
